title: Welcome to My Portfolio
logo: photo/My%20photo%202.jpeg
description: Showcasing projects, skills, and experience in data analysis using Excel, SQL, Power BI, Tableau, and more.
theme: jekyll-theme-cayman
